[project]
name = "vector-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Usama Bashir", email = "buttuxama@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=3.24.0",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "tqdm>=4.67.1",
]

[project.scripts]
ingest-pgvector = "vector_search.ingest_pgvector:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
